# Generated by Django 4.0.3 on 2025-07-30 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectingdb',
            name='promoperson',
        ),
        migrations.AlterField(
            model_name='collectingdb',
            name='address001',
            field=models.CharField(max_length=120, null=True, verbose_name='주소'),
        ),
        migrations.AlterField(
            model_name='collectingdb',
            name='cate001',
            field=models.CharField(choices=[('미용실', '미용실'), ('애견미용실', '애견미용실')], max_length=30, null=True, verbose_name='미용실/애견미용실'),
        ),
        migrations.AlterField(
            model_name='collectingdb',
            name='dhname',
            field=models.CharField(max_length=50, null=True, verbose_name='미용실명'),
        ),
    ]
