# Generated by Django 4.0.3 on 2025-07-31 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_collectingdb_promoperson_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectingdb',
            name='age',
            field=models.CharField(max_length=50, null=True, verbose_name='나이'),
        ),
        migrations.AlterField(
            model_name='collectingdb',
            name='address001',
            field=models.CharField(max_length=120, null=True, verbose_name='거주지'),
        ),
        migrations.AlterField(
            model_name='collectingdb',
            name='number',
            field=models.CharField(max_length=50, null=True, verbose_name='연락처'),
        ),
    ]
