# Generated by Django 4.0.3 on 2025-08-01 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_collectingdb_age_alter_collectingdb_address001_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectingdb',
            name='cate001',
        ),
        migrations.RemoveField(
            model_name='collectingdb',
            name='dhname',
        ),
    ]
