# Generated by Django 4.0.3 on 2025-08-03 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_collectingdb_cate001_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectingdb',
            name='body',
            field=models.TextField(null=True, verbose_name='내용'),
        ),
        migrations.AddField(
            model_name='collectingdb',
            name='cate001',
            field=models.CharField(choices=[('구매', '구매'), ('렌탈', '렌탈')], max_length=30, null=True, verbose_name='평형'),
        ),
        migrations.AddField(
            model_name='collectingdb',
            name='cate002',
            field=models.CharField(choices=[('구매', '구매'), ('렌탈', '렌탈')], max_length=30, null=True, verbose_name='평형'),
        ),
    ]
