# Generated by Django 4.0.3 on 2025-08-03 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_collectingdb_body_collectingdb_cate001_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectingdb',
            name='carnumbers',
            field=models.CharField(max_length=50, null=True, verbose_name='차량번호'),
        ),
        migrations.AddField(
            model_name='collectingdb',
            name='reservation',
            field=models.CharField(max_length=50, null=True, verbose_name='예약날짜'),
        ),
        migrations.AlterField(
            model_name='collectingdb',
            name='cate001',
            field=models.CharField(choices=[('모델하우스', '모델하우스'), ('홍보관', '홍보관')], max_length=30, null=True, verbose_name='모델하우스'),
        ),
        migrations.AlterField(
            model_name='collectingdb',
            name='cate002',
            field=models.CharField(choices=[('남성', '남성'), ('여성', '여성')], max_length=30, null=True, verbose_name='성별'),
        ),
    ]
