# Generated by Django 4.0.3 on 2025-08-03 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_collectingdb_carnumbers_collectingdb_reservation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectingdb',
            name='body',
        ),
        migrations.AlterField(
            model_name='collectingdb',
            name='cate001',
            field=models.CharField(choices=[('모델하우스', '모델하우스'), ('홍보관', '홍보관')], max_length=30, null=True, verbose_name='분류'),
        ),
    ]
