# Generated by Django 4.0.3 on 2025-08-03 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_collectingdb_body_alter_collectingdb_cate001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectingdb',
            name='age',
            field=models.CharField(choices=[('20대', '20대'), ('30대', '30대'), ('40대', '40대'), ('50대', '50대'), ('60대', '60대'), ('70대', '70대'), ('80대', '80대')], max_length=30, null=True, verbose_name='성별'),
        ),
    ]
