# Generated by Django 4.0.3 on 2025-08-07 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_collectingdb_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectingdb',
            name='address001',
        ),
        migrations.RemoveField(
            model_name='collectingdb',
            name='age',
        ),
        migrations.RemoveField(
            model_name='collectingdb',
            name='carnumbers',
        ),
        migrations.RemoveField(
            model_name='collectingdb',
            name='cate001',
        ),
        migrations.RemoveField(
            model_name='collectingdb',
            name='cate002',
        ),
        migrations.RemoveField(
            model_name='collectingdb',
            name='reservation',
        ),
    ]
